name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (Temurin is an OpenJDK distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven (skip tests for speed, or remove -DskipTests to run tests)
      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      # 4. Log in to Docker Hub (store DOCKERHUB_USERNAME & DOCKERHUB_PASSWORD as GitHub secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Build Docker image (tag it with the commit SHA for uniqueness)
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scheduling-service:${{ github.sha }} .

      # 6. Push Docker image (commit SHA tag)
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scheduling-service:${{ github.sha }}

      # 7. (Optional) Tag and push 'latest'
      - name: Tag and Push 'latest'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/scheduling-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/scheduling-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scheduling-service:latest
